# Generated by Django 4.2.6 on 2023-10-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hvm', '0002_alter_accompanying_image_alter_leadvisitor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accompanying',
            name='image',
        ),
    ]
