# Generated by Django 4.2.6 on 2023-10-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hvm', '0003_remove_accompanying_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accompanying',
            name='address',
        ),
        migrations.RemoveField(
            model_name='accompanying',
            name='company_name',
        ),
    ]
