# Generated by Django 4.2.6 on 2023-10-14 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hvm', '0004_remove_accompanying_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accompanying',
            name='unique_id',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
        migrations.AddField(
            model_name='leadvisitor',
            name='unique_id',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
