# Generated by Django 4.2.6 on 2023-10-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvm', '0005_accompanying_unique_id_leadvisitor_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadvisitor',
            name='visiting_date',
            field=models.DateField(blank=True, null=True, verbose_name='Visiting Date'),
        ),
        migrations.AlterField(
            model_name='leadvisitor',
            name='visiting_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Visiting Time'),
        ),
    ]
