# Generated by Django 4.2.6 on 2023-10-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvm', '0006_leadvisitor_visiting_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadvisitor',
            name='valid_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
