# Generated by Django 4.2.6 on 2023-10-20 12:44

from django.db import migrations, models
import hvm.models


class Migration(migrations.Migration):

    dependencies = [
        ('hvm', '0011_accompanying_email_leadvisitor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accompanying',
            name='lead_visitor',
        ),
        migrations.AddField(
            model_name='accompanying',
            name='lead_visitor_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=hvm.models.LeadVisitor),
        ),
    ]
