# Generated by Django 4.2.6 on 2023-10-20 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hvm', '0013_alter_accompanying_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accompanying',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accompanying_visitors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leadvisitor',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_visitors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivers', to=settings.AUTH_USER_MODEL),
        ),
    ]
