# Generated by Django 4.2.6 on 2023-10-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvm', '0014_alter_accompanying_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accompanying',
            name='lead_visitor_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
