# Generated by Django 4.2.6 on 2023-10-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvm', '0015_alter_accompanying_lead_visitor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadvisitor',
            name='image',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
