# Generated by Django 4.2.6 on 2023-10-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvm', '0018_accompanying_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadvisitor',
            name='official_documentation',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
