# Generated by Django 4.2.6 on 2023-10-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvm', '0019_leadvisitor_official_documentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadvisitor',
            name='visitee',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
