# Generated by Django 4.2.6 on 2023-10-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hvm', '0020_leadvisitor_visitee'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadvisitor',
            name='department',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
